steps:
- name: 'abdennour/eksctl:0.16.0-aws-1.18.39-kubectl-v1.18.1'
  entrypoint: 'bash'
  args: ['run.sh']
  secretEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']
timeout: 1800s
secrets:
- kmsKeyName: projects/kaygee-factory/locations/global/keyRings/keyring/cryptoKeys/key
  secretEnv:
    AWS_ACCESS_KEY_ID: CiQAJS+bVrmN7czo3sCc0WVWUyyvsBIGjMSxQkmo6dRQq7HBWP8SPQBWa0f+zj7C+0EY48Ird+EHMKzfzk2WsoG9XhP18oidldyhDin8y3KaqC93BWEaJ+wRxqfVmSRavCI2lZw=
    AWS_SECRET_ACCESS_KEY: CiQAJS+bVnMbn+cgujxCvPeQsBJcllQoeGia7To9dY1Ik63Kru8SUQBWa0f+pVuW+FQEIoOfSMvtNPpwXwoJzKOIjpJG1oEC7/VGtK+ZeRdxSWAt1ZnxO/WLF8lS7+mNorXalfIQTOBE14WC11vjHoeQUxsGDp25WQ==
